💄  day2

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1,23 +1,20 @@
-version: '3'
-x-airflow-common:
-  &airflow-common
+version: "3"
+x-airflow-common: &airflow-common
   image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.1.4}
-  environment:
-    &airflow-common-env
+  environment: &airflow-common-env
     AIRFLOW__CORE__EXECUTOR: LocalExecutor
     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
-    AIRFLOW__CORE__FERNET_KEY: ''
-    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
-    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
-    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
+    AIRFLOW__CORE__FERNET_KEY: ""
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
+    AIRFLOW__CORE__LOAD_EXAMPLES: "true"
+    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
     _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
   volumes:
     - ./dags:/opt/airflow/dags
     - ./logs:/opt/airflow/logs
     - ./plugins:/opt/airflow/plugins
   user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
-  depends_on:
-    &airflow-common-depends-on
+  depends_on: &airflow-common-depends-on
     postgres:
       condition: service_healthy
 
@@ -56,7 +53,11 @@ services:
     <<: *airflow-common
     command: scheduler
     healthcheck:
-      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
+      test:
+        [
+          "CMD-SHELL",
+          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"',
+        ]
       interval: 10s
       timeout: 10s
       retries: 5
@@ -66,77 +67,77 @@ services:
       airflow-init:
         condition: service_completed_successfully
 
-  # airflow-init:
-  #   <<: *airflow-common
-  #   entrypoint: /bin/bash
-  #   # yamllint disable rule:line-length
-  #   command:
-  #     - -c
-  #     - |
-  #       function ver() {
-  #         printf "%04d%04d%04d%04d" $${1//./ }
-  #       }
-  #       airflow_version=$$(gosu airflow airflow version)
-  #       airflow_version_comparable=$$(ver $${airflow_version})
-  #       min_airflow_version=2.1.0
-  #       min_airflow_version_comparable=$$(ver $${min_airflow_version})
-  #       if (( airflow_version_comparable < min_airflow_version_comparable )); then
-  #         echo
-  #         echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
-  #         echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
-  #         echo
-  #         exit 1
-  #       fi
-  #       if [[ -z "${AIRFLOW_UID}" ]]; then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
-  #         echo "If you are on Linux, you SHOULD follow the instructions below to set "
-  #         echo "AIRFLOW_UID and AIRFLOW_GID environment variables, otherwise files will be owned by root."
-  #         echo "For other operating systems you can get rid of the warning with manually created .env file:"
-  #         echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#setting-the-right-airflow-user"
-  #         echo
-  #       fi
-  #       one_meg=1048576
-  #       mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
-  #       cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
-  #       disk_available=$$(df / | tail -1 | awk '{print $$4}')
-  #       warning_resources="false"
-  #       if (( mem_available < 4000 )) ; then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
-  #         echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
-  #         echo
-  #         warning_resources="true"
-  #       fi
-  #       if (( cpus_available < 2 )); then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
-  #         echo "At least 2 CPUs recommended. You have $${cpus_available}"
-  #         echo
-  #         warning_resources="true"
-  #       fi
-  #       if (( disk_available < one_meg * 10 )); then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
-  #         echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
-  #         echo
-  #         warning_resources="true"
-  #       fi
-  #       if [[ $${warning_resources} == "true" ]]; then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
-  #         echo "Please follow the instructions to increase amount of resources available:"
-  #         echo "   https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin"
-  #         echo
-  #       fi
-  #       mkdir -p /sources/logs /sources/dags /sources/plugins
-  #       chown -R "${AIRFLOW_UID}:${AIRFLOW_GID}" /sources/{logs,dags,plugins}
-  #       exec /entrypoint airflow version
+  airflow-init:
+    <<: *airflow-common
+    entrypoint: /bin/bash
+    # yamllint disable rule:line-length
+    command:
+      - -c
+      - |
+        function ver() {
+          printf "%04d%04d%04d%04d" $${1//./ }
+        }
+        airflow_version=$$(gosu airflow airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.1.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo
+          exit 1
+        fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID and AIRFLOW_GID environment variables, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R "${AIRFLOW_UID}:${AIRFLOW_GID}" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow version
     # yamllint enable rule:line-length
     environment:
       <<: *airflow-common-env
-      _AIRFLOW_DB_UPGRADE: 'true'
-      _AIRFLOW_WWW_USER_CREATE: 'true'
+      _AIRFLOW_DB_UPGRADE: "true"
+      _AIRFLOW_WWW_USER_CREATE: "true"
       _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
       _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
     user: "0:${AIRFLOW_GID:-0}"
@@ -156,5 +157,46 @@ services:
       - -c
       - airflow
 
+  minio:
+    image: quay.io/minio/minio:RELEASE.2021-09-24T00-24-24Z
+    environment:
+      MINIO_ROOT_USER: minio
+      MINIO_ROOT_PASSWORD: minio123
+    ports:
+      - 9000:9000
+      - 9001:9001
+    volumes:
+      - minio-data-volume:/data
+    healthcheck:
+      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
+      interval: 30s
+      timeout: 20s
+      retries: 3
+    restart: always
+    command: server /data --console-address ":9001"
+
+  db:
+    image: postgres:13
+    environment:
+      - POSTGRES_USER=postgres
+      - POSTGRES_PASSWORD=postgres
+      - POSTGRES_DB=postgres
+    volumes:
+      - db-data-volume:/var/lib/postgresql/data
+    healthcheck:
+      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
+      timeout: 30s
+      interval: 5s
+      retries: 5
+    restart: always
+
+  mailhog:
+    image: mailhog/mailhog
+    ports:
+      # - 1025:1025
+      - 8025:8025
+
 volumes:
   postgres-db-volume:
+  minio-data-volume:
+  db-data-volume:
